### ISSUE TITLE
Not compatible with 9.10.0 of m4tthumphrey/php-gitlab-api

### ISSUE THREAD

**Issue by Fonata** [wemakecustom/gitlab-composer#33]
Problem: ``Uncaught TypeError: Argument 1 passed to Gitlab\Client::__construct() must be an instance of Gitlab\HttpClient\Builder, string given`` around line 40 of packages.php.

Solution: 
1. ``composer require php-http/curl-client guzzlehttp/psr7 php-http/message``
2. change `$client = new Client($confs['endpoint']);` to `$client = Client::create($confs['endpoint']);`
3. Around line 184, always call `->all` instead of `->accessible`, as the method [has been removed](https://github.com/m4tthumphrey/php-gitlab-api/blob/master/UPGRADE.md).

**Comment by Fonata** [comment]
Nevermind, I just realized you already updated this code. All is good & /close

**Comment by lemoinem** [comment]
@Fonata Thanks for opening (and closing ;) ) an issue and Thanks for your continued use of gitlab-composer. As you may have notice, this project is receiving very limited support.

In particular, in the future, if you do know what code changes are necessary, I would encourage you to submit a PR instead of creating an issue.
